### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by antoniodeluca** [scientilla/scientilla_v0#1]
Hi to all,

this codebase is not updated from more than 6 months while there are instead constant commits to the new repository (scientilla).
Is the this old codebase (scientilla_v0) to be considered a dead project with no more support from the core team?

Thanks for the help

**Comment by scientilla** [comment]
At the moment there is no plan to continue the development of the old codbase (scientilla_v0).

**Comment by antoniodeluca** [comment]
Ok, thanks.

**Comment by livia-b** [comment]
I am also interested in the status of the scientilla project. The new codebase doesn't have any readme file and the scientilla.net domain is expired (so it's not possible to download the binaries or see any screenshot). Is there any version (old or new) for the casual user to try out?

**Comment by antoniodeluca** [comment]
Hi to all,

I would like to continue on the path of developing a tool for the Open Science community (https://en.wikipedia.org/wiki/Open_science) that can be usable by any organization, scientist or person for improving security, discoverability and collaboration about world-wide research in general.

The original "scientilla_v0" work is a good starting point for this mission and I would like to reuse the amazing job done with it. 

It seems that there is no plan to continue the development of this old codebase and then, because I have been one of the inventors and I still believe that my old ideas could generate a good tool for the scientific community, I have decided to do an effort to bring it to the next level.

The new project, "scieHance - SCIEntific intercHange alliANCE", will be stored into the "https://github.com/antoniodeluca/sciehance" repository and will be constituted by an autonomous codebase able to interact with the "scientilla_v0" work and to add on top of it other functionalities. 

The interaction between the two different systems will be achieved through web services, database access and "same domain deployment" but without direct code merging and/or direct in-process communications.

In terms of the "scientilla_v0" project I will try, where possible, to keep the compatibility with the old codebase and vision, so that you could eventually get back some indirect contributions to it in the future, but it will have for sure to be also adapted in favour of the sciehance mission. 

Because of that the "scientilla_v0" codebase will continue to be developed through the "https://github.com/antoniodeluca/scientilla_v0" fork that will be connected to the "https://github.com/scientilla/scientilla_v0" repository so that clear attribution is made for transparency.

Changes to the "scientilla_v0" codebase will continue to be released under the MIT license and copyright will continue to be clearly and correctly attributed to "Fondazione Istituto Italiano di Tecnologia". 

Where and when the already existent codebase will be changed an additional information about the contributor(s) will be added in the starting part of each specific modified file so that the final user can understand "who has done what".

The new project will be released under the MIT license but a different copyright holder. It will be indeed, as already explained above, a totally separated entity from the old "scientilla_v0" project.

If you need further information about the scieHance project and/or if you would like to suggest possible directions for the changes to the "scientilla_v0" codebase, so that they can be of any help to you, please post issues through the specific github tools at "https://github.com/antoniodeluca/sciehance" and "https://github.com/antoniodeluca/scientilla_v0".

Thanks
